# Generated by Django 5.2.8 on 2025-11-06 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main_page', models.BooleanField(default=False, help_text='Define se esta é a página raiz do usuário', verbose_name='É Página Principal?')),
                ('title', models.CharField(default='Sem título', max_length=255, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True, verbose_name='Slug')),
                ('content', models.TextField(blank=True, help_text='Conteúdo em Markdown da página', verbose_name='Conteúdo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('parent_page', models.ForeignKey(blank=True, help_text='Página mãe na hierarquia (null se for página principal)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pages.page', verbose_name='Página Mãe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
                'ordering': ['-updated_at'],
            },
        ),
    ]
